# 1-qadam: React ilovani qadoqlash (Build)
FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2-qadam: Tezkor Nginx server orqali tayyor ilovani tarqatish va API so'rovlarni ulash
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# API larni Backend ga marshrutlash qoidasini yozamiz
RUN echo "server { listen 80; location / { root /usr/share/nginx/html; try_files \$uri /index.html; } location /api/ { proxy_pass http://backend:3000/api/; } }" > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
